name: Deploy to host

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy files via rsync
      uses: D3rHase/rsync-deploy-action@latest
      with:
        HOST: ${{ secrets.SERVER_HOST }}
        USER: ${{ secrets.SERVER_USER }}
        PRIVATE_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
        REPOSITORY_PATH: 'themes/*'
        SERVER_PATH: ${{ vars.DEPLOY_FOLDER }}

    - name: Notify Deployment Success
      run: echo "Deployment to ${{ secrets.HOST }} completed successfully!"